# Generated by Django 5.0.3 on 2024-03-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='Conversation',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='created_at',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationMessage',
        ),
    ]
